
- name: Ensure custom groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ custom_groups }}"

- name: Manage users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups | join(',') }}"
  loop: "{{ users }}"

- name: Add SSH key for user
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
